
[[_Usage]]
= Usage

The following sections describe how you may use this plugin in an project.

== Configuration

The plugin's <<_modules, module>> registers a `{api_wslite_handler}` helper class that defines the base contract
for issuing REST or SOAP calls using an appropriate client class. This helper class has the following methods

[source,java,options="nowrap"]
.griffon.plugins.wslite.WsliteHandler.java
----
include::{path_griffon_wslite_core}/src/main/java//griffon/plugins/wslite/WsliteHandler.java[tags=methods,indent=0]
----

The following properties will be set on the implicit `HTTPClient` when using either `withRest` or `withSoap`:

 * connectTimeout
 * readTimeout
 * followRedirects
 * useCaches
 * sslTrustAllCerts
 * sslTrustStoreFile
 * sslTrustStorePassword
 * proxy
 * httpConnectionFactory
 * authorization

These methods will create a new client when invoked unless you define an `id:` attribute. When this attribute is supplied
the client will be stored in a cache managed by their respective storage classes (`{api_restclient_storage}`, `{api_soapclient_storage}`).

You can inject an instance of `{api_wslite_handler}` anywhere it's needed using `@Inject`. There are two
callbacks you may use with these methods: either you work with a `wslite.rest.RESTClient` instance using `{api_restclient_callback}`
or with a `wslite.soap.SOAPClient` instance using `{api_soapclient_callback}`. Both options will come in handy with other plugins
or APIs that require one instance or the other.

Both callbacks are defined using a functional interface approach, which means you can apply lambda expressions if running
with JDK8+ or closures if running Groovy.

[source,java,options="nowrap"]
.griffon.plugins.wslite.WsliteCallback.java
----
include::{path_griffon_wslite_core}/src/main/java/griffon/plugins/wslite/RESTClientCallback.java[lines=28..-1]
----

[source,java,options="nowrap"]
.griffon.plugins.wslite.ConnectionCallback.java
----
include::{path_griffon_wslite_core}/src/main/java/griffon/plugins/wslite/SOAPClientCallback.java[lines=28..-1]
----

== Example

The following is a trivial usage of the `{api_wslite_handler}` paired with http://jdbi.org[JDBI, window="_blank"]
inside a service

[source,java,options="nowrap"]
.CalculatorService.java
----
include::{path_griffon_wslite_core}/src/test/groovy/griffon/plugins/wslite/CalculatorService.java[lines=18..-1]
----

== AST Transformation

You can apply the `{api_wslite_aware}` AST transformation on any class. This injects the behavior of `{api_wslite_handler}`
into said class.

== DSL Descriptors

This plugin provides DSL descriptors for Intellij IDEA and Eclipse (provided you have the Groovy Eclipse plugin installed).
These descriptors are found inside the `griffon-wslite-groovy-compile-{project-version}.jar`, with locations

 * dsdl/griffon_wslite.dsld
 * gdsl/griffon_wslite.gdsl
